import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className="min-h-screen overflow-x-hidden ">
        {/* <LenisScroll > */}
          <main className="flex-grow ">{children}</main>
        {/* </LenisScroll> */}
      </body>
    </html>
  );
}
